(ns com.star-empire-elite.schema)

(def schema
  {:user/id :uuid
   :user [:map {:closed true}
          [:xt/id                          :user/id]
          [:user/email                     :string]
          [:user/joined-at                 inst?]
          [:user/foo {:optional true}      :string]
          [:user/bar {:optional true}      :string]]

   :game/id :uuid
   :game [:map {:closed true}
          [:xt/id                          :game/id]
          [:game/name                      :string]
          [:game/created-at                inst?]
          [:game/scheduled-end-at          inst?]
          [:game/ended-at {:optional true} inst?]
          [:game/status                    :int]
          [:game/turns-per-day             :int]
          [:game/rounds-per-day            :int]
          
          ;; Planet Income Constants (per planet per round)
          [:game/ore-credits-per-planet    :int]   ; credits generated by ore planets
          [:game/ore-fuel-per-planet       :int]   ; fuel generated by ore planets
          [:game/ore-galaxars-per-planet   :int]   ; galaxars generated by ore planets
          [:game/food-per-planet           :int]   ; food generated by food planets
          [:game/mil-soldiers-per-planet   :int]   ; soldiers generated by military planets
          [:game/mil-fighters-per-planet   :int]   ; fighters generated by military planets
          [:game/mil-stations-per-planet   :int]   ; defence stations generated by military planets
          [:game/mil-agents-per-planet     :int]   ; agents generated by military planets
          
          ;; Expense Constants (per unit/planet per round)
          [:game/planet-credit-cost        :int]   ; credits cost per planet
          [:game/planet-food-cost          :int]   ; food cost per planet
          [:game/soldier-credit-cost-per-k :int]   ; credits per 1000 soldiers
          [:game/soldier-food-cost-per-k   :int]   ; food per 1000 soldiers
          [:game/fighter-credit-cost       :int]   ; credits per fighter
          [:game/fighter-fuel-cost         :int]   ; fuel per fighter
          [:game/station-credit-cost       :int]   ; credits per defence station
          [:game/station-fuel-cost         :int]   ; fuel per defence station
          [:game/agent-credit-cost         :int]   ; credits per agent
          [:game/agent-food-cost-per-k     :int]   ; food per 1000 agents
          [:game/pop-credit-cost-per-k     :int]   ; credits per 1000 population
          [:game/pop-food-cost-per-k       :int]   ; food per 1000 population
          
          ;; Starting Resources
          [:game/starting-credits          :int]
          [:game/starting-food             :int]
          [:game/starting-fuel             :int]
          [:game/starting-galaxars         :int]
          [:game/starting-population       :int]
          [:game/starting-stability        :int]
          
          ;; Starting Planets
          [:game/starting-military-planets :int]
          [:game/starting-food-planets     :int]
          [:game/starting-ore-planets      :int]
          
          ;; Starting Units
          [:game/starting-generals         :int]
          [:game/starting-admirals         :int]
          [:game/starting-soldiers         :int]
          [:game/starting-transports       :int]
          [:game/starting-defence-stations :int]
          [:game/starting-carriers         :int]
          [:game/starting-fighters         :int]
          [:game/starting-command-ships    :int]
          [:game/starting-agents           :int]]

   :player/id :uuid
   :player [:map {:closed true}
            [:xt/id                        :player/id]
            [:player/user                  :user/id]
            [:player/game                  :game/id]
            [:player/empire-name           :string]

            ;; Currencies
            [:player/credits               :int]
            [:player/food                  :int]
            [:player/fuel                  :int]
            [:player/galaxars              :int]
 
            ;; Resources
            [:player/military-planets      :int]
            [:player/food-planets          :int]
            [:player/ore-planets           :int]
            [:player/population            :int]

            ;; Status
            [:player/stability             :int]
            [:player/status                :int]
            [:player/score                 :int]

            ;; Turn/Round/Phase tracking
            [:player/current-turn          :int]
            [:player/current-round         :int]
            [:player/current-phase         :int]
            [:player/turns-used            :int]
            [:player/last-turn-at
             {:optional true}              inst?]
 
            ;; Leadership

            ;; Military units
            [:player/soldiers              :int]
            [:player/transports            :int]
            [:player/defence-stations      :int]
            [:player/carriers              :int]
            [:player/fighters              :int]
            [:player/command-ships         :int]
            [:player/generals              :int]
            [:player/admirals              :int]
            [:player/agents                :int]

            ;; Diplomatic relationships
            [:player/allies {:optional true}   [:set :player/id]]
            [:player/treaties {:optional true} [:set :player/id]]
            [:player/messages {:optional true} [:vector :message/id]]]

   :message/id :uuid
   :message [:map {:closed true}
             [:xt/id              :message/id]
             [:message/game       :game/id]
             [:message/from       :player/id]
             [:message/to         :player/id]
             [:message/text       :string]
             [:message/sent-at    inst?]
             [:message/is-anonymous :boolean]]})

(def module
  {:schema schema})
