;;;;;
;;;;; Income Phase - Resource Generation
;;;;;
;;;;; The income phase is the first phase of each turn where players collect resources from their
;;;;; planets and any other sources. Unlike later phases (expenses, exchange, building), the income
;;;;; phase requires no player decisions; it's purely informational, showing what resources will be
;;;;; generated before the player advances to the next phase.
;;;;;

(ns com.star-empire-elite.pages.app.income
  (:require [com.biffweb :as biff]
            [com.star-empire-elite.ui :as ui]
            [com.star-empire-elite.utils :as utils]))

;;;;
;;;; Calculations
;;;;

(defn calculate-income
  "Calculate income from all sources using game constants.

  [player game] -> {:ore-credits int, :ore-fuel int,
                    :food-food int, :mil-soldiers int, :mil-fighters int,
                    :mil-stations int, :tax-credits int}"
  [player game]
  ;; Keys such as :player/ore-planets are fully qualified keys in the player map.
  ;; That is, there is a key in the player map named :player/ore-planets, etc.
  ;;             (* resource-count-for-player     resource-value-in-game)
  {:ore-credits  (* (:player/ore-planets player)  (:game/ore-planet-credits game))
   :ore-fuel     (* (:player/ore-planets player)  (:game/ore-planet-fuel game))
   :food-food    (* (:player/food-planets player) (:game/food-planet-food game))
   :mil-soldiers (* (:player/mil-planets player)  (:game/mil-planet-soldiers game))
   :mil-fighters (* (:player/mil-planets player)  (:game/mil-planet-fighters game))
   :mil-stations (* (:player/mil-planets player)  (:game/mil-planet-stations game))
   :tax-credits  (* (:player/population player)   (:game/population-tax-credits game))})

;;;;
;;;; UI Components
;;;;

(defn income-row
  "Renders an income row showing resources generated by a planet type.

  Uses custom mobile/desktop layouts optimized for income display:
  - Mobile:  Compact grid showing planet type, count, and non-zero resources only
  - Desktop: Full table row with all columns, zero values dimmed at 20% opacity

  [planet-type-name str, planet-count int, income-map {:credits? int, :fuel? int, ...}] -> hiccup"
  [planet-type-name planet-count income-map]
  [:div.border-b.border-green-400.last:border-b-0

   ;; Mobile: Compact grid with narrower planet type column
   [:div.grid.gap-1.px-2.py-2.items-center.text-xs.leading-tight.lg:hidden
    {:style {:grid-template-columns "0.5fr 0.4fr 4fr"}}  ; Reduced first two columns, expanded last

    ;; Planet type
    [:div.font-mono planet-type-name]

    ;; Planet count (formatted with parentheses)
    [:div.text.font-mono "(" (ui/format-number planet-count) ")"]

    ;; Resources - all in one column, spaced out
    [:div.flex.gap-3.justify-start.flex-wrap
     (for [[k label] [[:credits "Crds"] [:fuel "Fuel"]
                      [:food "Food"] [:soldiers "Sold"] [:fighters "Fghts"]
                      [:stations "Stns"]]
           :let [v (or (k income-map) 0)]
           :when (pos? v)]
       [:div.whitespace-nowrap {:key k}
        [:span.text-green-300 label]
        [:span.font-mono.ml-1 "+" (ui/format-number v)]])]]

   ;; Desktop: Full table row with formatted planet count
   [:div.hidden.lg:grid.lg:gap-4.lg:items-center.lg:px-4.lg:py-3
    {:style {:grid-template-columns "repeat(8, minmax(0, 1fr))"}}
    [:div planet-type-name]
    [:div (ui/format-number planet-count)]
    (for [k [:credits :fuel :food :soldiers :fighters :stations]
          :let [v (or (k income-map) 0)]]
      [:div {:key k}
       [:span.font-mono {:style {:word-spacing "-0.2em"}
                         :class (when (zero? v) "opacity-20")}
        "+" (ui/format-number v)]])]])

;;;;
;;;; Actions
;;;;

(defn apply-income
  "Apply planet income to the player and advance to the expenses phase.
  Resets current-round to 1 when last-round-completed-at is from a previous UTC calendar day,
  covering both the all-rounds-used and skipped-round cases.

  [ctx ring-ctx] -> ring-response (303 redirect to expenses)"
  ;; ctx is the Biff context map. :keys destructures that map to pull out commonly-used keys, while
  ;; keeping the full map bound to ctx so we can pass it to utils/with-player-and-game and 
  ;; biff/submit-tx.
  [{:keys [path-params biff/db] :as ctx}]
  (utils/with-player-and-game [player game player-id] ctx
    (if-let [redirect (utils/validate-phase player 1 player-id)]
      redirect
      (let [income         (calculate-income player game)
            last-completed (:player/last-round-completed-at player)
            day-reset?     (and (> (:player/current-round player) 1)
                                last-completed
                                (not (utils/same-calendar-day? last-completed)))]
        (biff/submit-tx ctx
          [(cond-> {:db/doc-type          :player
                    :db/op                :update
                    :xt/id                player-id
                    :player/credits       (+ (:player/credits player)  (:ore-credits income) (:tax-credits income))
                    :player/food          (+ (:player/food player)     (:food-food income))
                    :player/fuel          (+ (:player/fuel player)     (:ore-fuel income))
                    :player/soldiers      (+ (:player/soldiers player) (:mil-soldiers income))
                    :player/fighters      (+ (:player/fighters player) (:mil-fighters income))
                    :player/stations      (+ (:player/stations player) (:mil-stations income))
                    :player/current-phase 2}
                   day-reset? (assoc :player/current-round 1))])
        {:status 303
         :headers {"location" (str "/app/game/" player-id "/expenses")}}))))

(defn income-page
  "Show income preview for the current turn. No player decisions required — income is informational 
  only, so no htmx dynamic updates are needed.

  [{:keys [player game]}] -> hiccup"
  [{:keys [player game]}]
  (let [income (calculate-income player game)]
    (ui/page
      {}
      [:div.text-green-400.font-mono
       [:h1.text-3xl.font-bold.mb-6 (:player/empire-name player)]

       ;;; Current phase display:
       (ui/phase-header (:player/current-phase player) "INCOME"
                        (str "Turn " (:player/current-turn player) " | Round " (:player/current-round player)))

       ;;; Current resources display:
       ;;; Shows starting position before income is applied, helping players understand what they have
       ;;; available for the upcoming expenses phase.
       (ui/resource-display-grid player "Resources Before Income")

       ;;; Income breakdown table:
       ;;; Displays as spreadsheet: normal on wide screen; compressed on mobile
       ;;; This makes it clear which planets generate which resources.
       [:h3.font-bold.mb-4 "Income"]
       [:div.border.border-green-400.mb-8
        ;; Header row (only visible on wide screens)
        (ui/phase-table-header ["Source" "Count" "Credits" "Fuel" "Food" "Soldiers" "Fighters" "Stations"])

        ;; Ore planets generate economic resources: credits and fuel
        (income-row "Ore"
                    (:player/ore-planets player)
                    {:credits (:ore-credits income)
                     :fuel    (:ore-fuel income)})

        ;; Food planets have a single output: food for feeding the population and the military
        (income-row "Food"
                    (:player/food-planets player)
                    {:food (:food-food income)})

        ;; Military planets generate military units: soldiers, fighters, and stations
        (income-row "Mil"
                    (:player/mil-planets player)
                    {:soldiers (:mil-soldiers income)
                     :fighters (:mil-fighters income)
                     :stations (:mil-stations income)})

        ;; Population generates tax revenue in credits (population stored in millions)
        (income-row "Pop"
                    (* (:player/population player) 1000000)
                    {:credits (:tax-credits income)})]

       ;;; Final resource totals:
       ;;; Shows what the player will have after income is applied. This preview helps players
       ;;; anticipate actions that they might want or need to take in the subsequent phases.
       (ui/resource-display-grid
         {:credits  (+ (:player/credits player)  (:ore-credits income) (:tax-credits income))
          :food     (+ (:player/food player)     (:food-food income))
          :fuel     (+ (:player/fuel player)     (:ore-fuel income))
          :galaxars (:player/galaxars player)
          :soldiers (+ (:player/soldiers player) (:mil-soldiers income))
          :fighters (+ (:player/fighters player) (:mil-fighters income))
          :stations (+ (:player/stations player) (:mil-stations income))
          :agents   (:player/agents player)}
         "Resources After Income")

       ;;; Phase Advance Form:
       ;;; Simple form submission with no validation needed. Income is always valid and beneficial.
       ;;; No htmx dynamic updates (unlike later phases) since there are no player choices to
       ;;; validate.
       (ui/incoming-alert player)

       (biff/form
         {:action (str "/app/game/" (:xt/id player) "/apply-income") :method "post"}
         [:div.flex.gap-4.mt-6
          [:a.border.border-green-400.px-6.py-2.hover:bg-green-400.hover:bg-opacity-10.transition-colors
           {:href (str "/app/game/" (:xt/id player))} "Pause"]
          [:button.bg-green-400.text-black.px-6.py-2.font-bold.hover:bg-green-300.transition-colors
           {:type "submit"} "Continue to Expenses"]])])))
